### ISSUE TITLE
API seems to not be available

### ISSUE THREAD

**Issue by fahlmant** [coreos/quartermaster#88]
I ran the following command from the README (changed the namespace to `storage` for my test cluster).
`kubectl run -n storage kube-qm --image=quay.io/lpabon/qm`

However, when walking through the GlusterFS examples, the API seems to be unavailable and the cluster cannot get the TPR for `StorageCluster`. I wget-ed the cluster.yaml, and changed the hostnames and IPs to match nodes within my cluster. 

```
$ wget https://raw.githubusercontent.com/lpabon/quartermaster/master/examples/glusterfs/cluster.yaml
$ kubectl get all -n storage
NAME                          READY     STATUS             RESTARTS   AGE
po/kube-qm-1394339067-qsgpd   0/1       CrashLoopBackOff   14         49m

NAME             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-qm   1         1         1            0           49m

NAME                    DESIRED   CURRENT   READY     AGE
rs/kube-qm-1394339067   1         1         0         49m
$ kubectl create -n storage -f cluster.yaml 
error: unable to recognize "cluster.yaml": no matches for storage.coreos.com/, Kind=StorageCluster
```

**Comment by fahlmant** [comment]
Using the default namespace, `kube-system`, fixed this issue. Is this expected behavior, or should user be able to define a namespace?

**Comment by lpabon** [comment]
Did you create a namespace using the UI or by submitting a [namespace object](https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/) ?

**Comment by fahlmant** [comment]
I created the storage namespace by running 
`kubectl create namespace storage`

**Comment by lpabon** [comment]
Correct I have only tried deploying qm on kube-system namespace. I would suggest running it there, then running the actual storage containers on the other namespaces. I'll keep this issue open until I investigate this further
